name: Push File
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Pushes french CV
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'french.pdf'
        destination_repo: 'tms-gvd/tms-gvd.github.io'
        destination_folder: 'assets/pdf'
        user_email: 'thomas.gaviard@gmail.com'
        user_name: 'tms-gvd'
        commit_message: 'Automatic update french CV'
        destination_branch: 'master'

    - name: Pushes english CV
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'english.pdf'
        destination_repo: 'tms-gvd/tms-gvd.github.io'
        destination_folder: 'assets/pdf'
        user_email: 'thomas.gaviard@gmail.com'
        user_name: 'tms-gvd'
        commit_message: 'Automatic update of english CV'
        destination_branch: 'master'